package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.GroupModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface GroupModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    int insert(GroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    GroupModel selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    List<com.zs.SmartTeam.model.GroupModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    int updateByPrimaryKey(GroupModel record);
}
