package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.PermissionModel;
import java.util.List;

public interface PermissionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun Dec 22 09:32:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun Dec 22 09:32:54 CST 2019
     */
    int insert(PermissionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun Dec 22 09:32:54 CST 2019
     */
    PermissionModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun Dec 22 09:32:54 CST 2019
     */
    java.util.List<com.zs.SmartTeam.model.PermissionModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun Dec 22 09:32:54 CST 2019
     */
    int updateByPrimaryKey(PermissionModel record);
}