package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.RequirementManagementModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RequirementManagementModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement-management
     *
     * @mbggenerated Fri May 10 04:58:38 CST 2019
     */
    int deleteByPrimaryKey(Long requirementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement-management
     *
     * @mbggenerated Fri May 10 04:58:38 CST 2019
     */
    int insert(RequirementManagementModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement-management
     *
     * @mbggenerated Fri May 10 04:58:38 CST 2019
     */
    RequirementManagementModel selectByPrimaryKey(Long requirementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement-management
     *
     * @mbggenerated Fri May 10 04:58:38 CST 2019
     */
    List<RequirementManagementModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement-management
     *
     * @mbggenerated Fri May 10 04:58:38 CST 2019
     */
    int updateByPrimaryKey(RequirementManagementModel record);

    /**
     * select all requirement document by author id
     *
     * @param requirementAuthor
     * @return
     */
    List<RequirementManagementModel> selectByAuthor(Long requirementAuthor);
}
