package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.RoleModel;
import java.util.List;

public interface RoleModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 22 09:32:33 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 22 09:32:33 CST 2019
     */
    int insert(RoleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 22 09:32:33 CST 2019
     */
    RoleModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 22 09:32:33 CST 2019
     */
    java.util.List<com.zs.SmartTeam.model.RoleModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 22 09:32:33 CST 2019
     */
    int updateByPrimaryKey(RoleModel record);
}