package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.ShareManagementModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ShareManagementModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_management
     *
     * @mbggenerated Fri May 10 04:59:02 CST 2019
     */
    int deleteByPrimaryKey(Long shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_management
     *
     * @mbggenerated Fri May 10 04:59:02 CST 2019
     */
    int insert(ShareManagementModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_management
     *
     * @mbggenerated Fri May 10 04:59:02 CST 2019
     */
    ShareManagementModel selectByPrimaryKey(Long shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_management
     *
     * @mbggenerated Fri May 10 04:59:02 CST 2019
     */
    List<ShareManagementModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_management
     *
     * @mbggenerated Fri May 10 04:59:02 CST 2019
     */
    int updateByPrimaryKey(ShareManagementModel record);
}
