package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.TaskGroupExtModel;
import java.util.List;

public interface TaskGroupExtModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_group_ext
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_group_ext
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    int insert(TaskGroupExtModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_group_ext
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    TaskGroupExtModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_group_ext
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    List<com.zs.SmartTeam.model.TaskGroupExtModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_group_ext
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    int updateByPrimaryKey(TaskGroupExtModel record);
}
