package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.UserRoleHrefModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserRoleHrefModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_href
     *
     * @mbggenerated Tue May 07 09:17:11 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_href
     *
     * @mbggenerated Tue May 07 09:17:11 CST 2019
     */
    int insert(UserRoleHrefModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_href
     *
     * @mbggenerated Tue May 07 09:17:11 CST 2019
     */
    UserRoleHrefModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_href
     *
     * @mbggenerated Tue May 07 09:17:11 CST 2019
     */
    List<UserRoleHrefModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_href
     *
     * @mbggenerated Tue May 07 09:17:11 CST 2019
     */
    int updateByPrimaryKey(UserRoleHrefModel record);

    /**
     * find user role code by user login names
     *
     * @param userLoginName
     * @return
     */
    List<String> selectRoleByLoginName (String userLoginName);
}
