package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.UserModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    UserModel selectByPrimaryKey(Long userId);

    /**
     *
     * get user by login name
     *
     * @param loginName
     * @return
     */
    UserModel selectByLoginName(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    List<UserModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    int updateByPrimaryKey(UserModel record);
}
