package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.UserRoleModel;
import java.util.List;

public interface UserRoleModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Dec 22 09:29:52 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Dec 22 09:29:52 CST 2019
     */
    int insert(UserRoleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Dec 22 09:29:52 CST 2019
     */
    UserRoleModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Dec 22 09:29:52 CST 2019
     */
    java.util.List<com.zs.SmartTeam.model.UserRoleModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Dec 22 09:29:52 CST 2019
     */
    int updateByPrimaryKey(UserRoleModel record);
}