package com.zs.SmartTeam.mapper;

import com.zs.SmartTeam.model.UserModel;
import java.util.List;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    UserModel selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    java.util.List<com.zs.SmartTeam.model.UserModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 04 06:23:37 CST 2019
     */
    int updateByPrimaryKey(UserModel record);
}