package com.zs.SmartTeam.model;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class DesignManagementModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_management.design_id
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    private Long designId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_management.design_content
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    private String designContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_management.design_author
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    private Long designAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_management.create_date
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_management.update_date
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_management.design_title
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    private String designTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_management.design_id
     *
     * @return the value of design_management.design_id
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public Long getDesignId() {
        return designId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_management.design_id
     *
     * @param designId the value for design_management.design_id
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public void setDesignId(Long designId) {
        this.designId = designId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_management.design_content
     *
     * @return the value of design_management.design_content
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public String getDesignContent() {
        return designContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_management.design_content
     *
     * @param designContent the value for design_management.design_content
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public void setDesignContent(String designContent) {
        this.designContent = designContent == null ? null : designContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_management.design_author
     *
     * @return the value of design_management.design_author
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public Long getDesignAuthor() {
        return designAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_management.design_author
     *
     * @param designAuthor the value for design_management.design_author
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public void setDesignAuthor(Long designAuthor) {
        this.designAuthor = designAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_management.create_date
     *
     * @return the value of design_management.create_date
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_management.create_date
     *
     * @param createDate the value for design_management.create_date
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_management.update_date
     *
     * @return the value of design_management.update_date
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_management.update_date
     *
     * @param updateDate the value for design_management.update_date
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_management.design_title
     *
     * @return the value of design_management.design_title
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public String getDesignTitle() {
        return designTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_management.design_title
     *
     * @param designTitle the value for design_management.design_title
     *
     * @mbggenerated Fri May 10 04:56:49 CST 2019
     */
    public void setDesignTitle(String designTitle) {
        this.designTitle = designTitle == null ? null : designTitle.trim();
    }
}
