package com.zs.SmartTeam.model;

import org.springframework.stereotype.Component;

@Component
public class GroupModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_id
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_name
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_id
     *
     * @return the value of group.group_id
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_id
     *
     * @param groupId the value for group.group_id
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_name
     *
     * @return the value of group.group_name
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_name
     *
     * @param groupName the value for group.group_name
     *
     * @mbggenerated Sat May 04 21:13:39 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }
}
