package com.zs.SmartTeam.model;

import java.util.Date;

public class ShareManagementModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_management.share_id
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    private Long shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_management.share_content
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    private String shareContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_management.share_author
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    private Long shareAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_management.create_date
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_management.update_date
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_management.share_id
     *
     * @return the value of share_management.share_id
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public Long getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_management.share_id
     *
     * @param shareId the value for share_management.share_id
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public void setShareId(Long shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_management.share_content
     *
     * @return the value of share_management.share_content
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public String getShareContent() {
        return shareContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_management.share_content
     *
     * @param shareContent the value for share_management.share_content
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public void setShareContent(String shareContent) {
        this.shareContent = shareContent == null ? null : shareContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_management.share_author
     *
     * @return the value of share_management.share_author
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public Long getShareAuthor() {
        return shareAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_management.share_author
     *
     * @param shareAuthor the value for share_management.share_author
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public void setShareAuthor(Long shareAuthor) {
        this.shareAuthor = shareAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_management.create_date
     *
     * @return the value of share_management.create_date
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_management.create_date
     *
     * @param createDate the value for share_management.create_date
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_management.update_date
     *
     * @return the value of share_management.update_date
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_management.update_date
     *
     * @param updateDate the value for share_management.update_date
     *
     * @mbggenerated Sat May 04 21:25:22 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}