package com.zs.SmartTeam.model;

public class TaskGroupExtModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_group_ext.id
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_group_ext.task_belonged
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    private Long taskBelonged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_group_ext.group_belonged
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    private Long groupBelonged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_group_ext.numerical_order
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    private Long numericalOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_group_ext.task_url
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    private String taskUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_group_ext.id
     *
     * @return the value of task_group_ext.id
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_group_ext.id
     *
     * @param id the value for task_group_ext.id
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_group_ext.task_belonged
     *
     * @return the value of task_group_ext.task_belonged
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public Long getTaskBelonged() {
        return taskBelonged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_group_ext.task_belonged
     *
     * @param taskBelonged the value for task_group_ext.task_belonged
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public void setTaskBelonged(Long taskBelonged) {
        this.taskBelonged = taskBelonged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_group_ext.group_belonged
     *
     * @return the value of task_group_ext.group_belonged
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public Long getGroupBelonged() {
        return groupBelonged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_group_ext.group_belonged
     *
     * @param groupBelonged the value for task_group_ext.group_belonged
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public void setGroupBelonged(Long groupBelonged) {
        this.groupBelonged = groupBelonged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_group_ext.numerical_order
     *
     * @return the value of task_group_ext.numerical_order
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public Long getNumericalOrder() {
        return numericalOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_group_ext.numerical_order
     *
     * @param numericalOrder the value for task_group_ext.numerical_order
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public void setNumericalOrder(Long numericalOrder) {
        this.numericalOrder = numericalOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_group_ext.task_url
     *
     * @return the value of task_group_ext.task_url
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public String getTaskUrl() {
        return taskUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_group_ext.task_url
     *
     * @param taskUrl the value for task_group_ext.task_url
     *
     * @mbggenerated Sat May 04 21:18:11 CST 2019
     */
    public void setTaskUrl(String taskUrl) {
        this.taskUrl = taskUrl == null ? null : taskUrl.trim();
    }
}